### ISSUE TITLE
Can't drag frameworks into my project

### ISSUE THREAD

**Issue by cnowak7** [mattdonnelly/Swifter#121]
I keep trying to drag your SwiftiOS.framework into my project, but it keeps saying that it can't be moved because there is no such file. In your demo Xcode project, your frameworks appear as red for some reason. 

Any thoughts on why?

**Comment by zntfdr** [comment]
Hi @cnowak7 ,
I don't have my mac with me so I can't try, however, If I remember correctly, all you need to do is:
# 1
Drop the *Swifter/* folder in your project.
# 2
add this line in your Bridging Header:
```C
  #import "Swifter/Swifter-Bridging-Header.h"
```
If you don't have one, just create a new *Header File* "*NamethisWhateverYouWant.h*" in your root folder (or anywhere you want, just remember to change the path correctly) with inside written:
```C
#ifndef import_c_Headers
    #define import_c_Headers
    #import "Swifter/Swifter-Bridging-Header.h"
#endif
```
# 3
Update your Target’s Build Settings to reference to the  "*NamethisWhateverYouWant.h*" Header File.
In order to do so, open your project Building Settings tab and in the *Swift Compiler* section, set to *yes* the  *Install Objective-C Compatibility Header* parameter and "*NamethisWhateverYouWant.h*" into the  *Objective-C bridging Header* parameter.

# 4
Enjoy!

Please let me know if it works!

**Comment by cnowak7** [comment]
Thanks! I'll try this right now, I'll get back to you in a few minutes.

**Comment by cnowak7** [comment]
This worked! How did it work without adding the frameworks to my project? I don't see the frameworks anywhere in my project right now.

**Comment by zntfdr** [comment]
I'm glad it helped!

By doing it this way, you manually imported the Swifter libraries in your project, no frameworks involved ;).

Cheers!

**Comment by cnowak7** [comment]
Wow, thanks a ton! That was a pretty neat trick.

**Comment by cnowak7** [comment]
@zntfdr Sorry to bug you again, but I have encountered a problem. The app works when I run on the simulator, but when I try to run it on my device, I get the following:

![screen shot 2016-01-10 at 12 43 37 am](https://cloud.githubusercontent.com/assets/11897465/12220306/7115007a-b733-11e5-9abd-4276869d3d32.png)

**Comment by zntfdr** [comment]
Because it's looking for a framework (iOSSwifter) that is not there. 
This is a leftover parameter from your previous tests. You should remove it from your building settings.
PSI'm typing this on my phone so I can't help much more than this.

**Comment by cnowak7** [comment]
Aaaaaaah ok I see it. I thought I removed it originally but I guess I forgot. That's a palm face for myself...lol. I removed it from from my "link with binary files" section of the build settings and it worked. Thanks!

**Comment by zntfdr** [comment]
You're welcome!Good luck with your app 😊
Cheers,Federico
