### ISSUE TITLE
Getting image from twitter api 

### ISSUE THREAD

**Issue by flamme0011** [mattdonnelly/Swifter#136]
Hi All,

I am getting tweet with image from twitter api. Everyting is ok I can get the tweet images and show them in screen but there is a performance problem. It takes so much time. I am showing images in tableview and show 5 tweet text and image in screen.

 let data = NSData(contentsOfURL: imageDataUrl) -> this line has performance problem.

Is there any way to fast it?
If I use Alamofire it can help me?

Thanks.

**Comment by zntfdr** [comment]
Hi @flamme0011 , that instruction blocks the program:
it's very slow because it downloads the picture from Internet and, only when it is finished downloading, it let you use the program again (unlock the UI, etc).

It's very bad for the user experience, luckily there are ways to fix the problem:
personally I'm using this solution, if somebody knows better ways, please let me know:

`````swift
dispatch_async(dispatch_get_global_queue(Int(QOS_CLASS_UTILITY.rawValue), 0)) { [weak self] in
    guard let data = NSData(contentsOfURL: imageDataUrl) else { return } 
    // ^ this blocks the thread it is on
    
    dispatch_async(dispatch_get_main_queue()) { [weak self] in
        // display image with instruction like
        self?.image = UIImage(data: data)
    }
}
`````

I'll write an explanation when I get off from work, in the meanwhile, you can start using the code above :smile:

**Comment by meteochu** [comment]
This issue was answered almost 12 months ago and will now be closed.
