### ISSUE TITLE
Odd behaviour with SwifteriOS.JSON.integer

### ISSUE THREAD

**Issue by josephbeuysmum** [mattdonnelly/Swifter#164]
I've just seen an odd behaviour. I don't have the time or knowledge to address it myself right now, so just reporting it. I used Swifter to download this tweet:

https://twitter.com/JosephBeuysMum/status/796713882274426880

That has this one embedded in it:

https://twitter.com/guardian/status/796712362162225153

And did the following to the resulting JSON:

```
let swifter = Swifter( account: myACAccount )

swifter.getHomeTimeline(
	count: maxTweets,
	sinceID: nil,
	maxID: maxId,
	trimUser: false,
	contributorDetails: true,
	includeEntities: true,
	success:
    {
        [ unowned self ] 
        ( tweetJson: SwifteriOS.JSON ) -> Void in
        self._set( tweets: tweetJson )
    }
)

fileprivate func _set ( tweets tweetJson: SwifteriOS.JSON )
{
	guard let tweetsArray = tweetJson.array else { return nil }
    
	for i in 0..<tweetsArray.count
	{
		let tweetJson = tweetsArray[ i ].object
		let tweet = _createTweetFrom( json: tweetJson )
    }
}

fileprivate func _createTweetFrom ( tweetJson: Dictionary< String, SwifteriOS.JSON > ) -> MyTweetObject?
{
    if 
    let embeddedTweetJson = tweetJson[ "quoted_status" ]?.object,
    let embeddedTweetId = embeddedTweetJson[ "id" ]?.integer,
    let embeddedTweetIdStr = embeddedTweetJson[ "id_str" ]?.string
    {
        print( embeddedTweetId, embeddedTweetIdStr )
    }
}
```

This is the result:

```
796712362162225152 796712362162225153
```

Two slightly different IDs, the second of which is correct, the first of which is not.

**Comment by meteochu** [comment]
This is not a problem with Swifter, but by Twitter itself. Due to Int32/Int64 problems, the `id` (Int) property from Twitter is often unreliable. Twitter suggests everyone to use the `id_str` property as it will always be the correct one.

For example, I just tried to fetch the exact same tweet, and the `id` property I got form the embeddedTweet JSON is `796712362162225200` (which is again, different from what you have)
