### ISSUE TITLE
Single callback with Result for success/failure

### ISSUE THREAD

**Issue by harlanhaskins** [mattdonnelly/Swifter#188]
In my usage of Swifter, I find myself having to duplicate code between the success and failure blocks a lot.

```swift
let semaphone = DispatchSemaphore(value: 0)
twitter.getTimeline(for: "...user...", sinceID: latestID,
    success: { json in
        let tweet = // do something with json
        twitter.postTweet(status: tweet, inReplyToStatusID: id,
            success: { json in
                semaphore.signal()
            },
            failure: { error in
                semaphore.signal()
            })
    },
    failure: { error in
      semaphore.signal()
    })
```

Apple's APIs usually speak in terms of a single `completionHandler` block that contains `(T?, Error?)`, but this is less than ideal. I think in Swift we can do much better using a `Result<T>` enum:

```swift
enum Result<T> {
    case success(T)
    case error(Error) 
}

twitter.postTweet(status: tweet) { result in
  switch result {
  case let .success(json):
      print(json)
  case let .failure(error):
      print(error)
  }
}
```

This way we:
 - have to handle failures, and
 - have a single point where each callback will go

Thoughts?

**Comment by zntfdr** [comment]
I like this idea.

However, like you've point out, at the moment you can ignore the failure (by ignoring its parameter), meanwhile with your proposal people always must manage both cases (at the very least by adding a `` guard case .success(let json) = result else { return }``, if you really want to ignore failures).

I tend to agree with your proposal, let's see what others think.

**Comment by meteochu** [comment]
I understand that the current method of separating `success` and `failure` is not the best way to deal with completionHandlers, and I've personally experimented with other methods in my own projects and abandoned branches of my own Swifter fork.

I very much like the `enum Result<T> { ... }`  method of handling completion handlers, so much so that I actually use it in my own personal Twitter project. It's definitely something to explore. The biggest problem is that switching to a new method will completely break all existing projects using Swifter. We have to consider migration methods before implementing this.
