### ISSUE TITLE
Cursor Values Throw Error

### ISSUE THREAD

**Issue by MdBee** [mattdonnelly/Swifter#70]
I believe the previous and next cursor values returned by

`getFriendsListWithScreenName(screenName: String, cursor: Int?, count: Int?, skipStatus: Bool?, includeUserEntities: Bool?, success: ((users: [JSONValue]?, previousCursor: Int?, nextCursor: Int?) -> Void)?, failure: FailureHandler?)`

are the reason I get this error

`fatal error: floating point value can not be converted to Int because it is greater than Int.max`

I've been using 200 as my requested count (the max allowed by Twitter).  When the list is not very big (e.g. 'nasa_neemo' follows 59 users) the request works fine.  I believe that's because there are no cursors returned.  But 'nasa' follows 230 users and throws the error.

Am I doing something wrong?  Are others using cursors returned from this function successfully?  thanks

**Comment by nilswiersema** [comment]
This is related to 32/64-bit integers. Swifter is currently unable to parse 64-bit integers on 32-bit platforms as `Swifter.JSON.integer` uses the `Swift.Int` type, whose maximum range depends on the platform.

Twitter cursors can actually go into the 64-bit range and Swifter tries to parse such cursors with `integer`, leading to the aforementioned error on 32-bit platforms. I found this out when executing the exact same API call app on an iPhone 5 instead of the simulator.

A solution to this problem is to use a 64-bit integer type, or to treat cursors as raw strings - just like Swifter already does for user IDs. I will submit a pull request later this week. Cheers!
