### ISSUE TITLE
JSON.JSONNull go through the optional binding

### ISSUE THREAD

**Issue by gecko655** [mattdonnelly/Swifter#94]
Against my expectation, ``.JSONNull`` is not filtered out by the optional binding.

For example:
```swift
let a :JSON? = .JSONNull
if let b = a {
  println(b)  // -> It prints "null"
}
````

So, especially when using streaming API,  I received ```.JSONNull``` from the request handler methods very frequently.

And my suggestion, should the ```.JSONNull``` be eliminated by the caller of JSON.parseJSONData()?
These are my suggestion to filter out ```.JSONNull``` (but maybe not comprehensive)
https://github.com/mattdonnelly/Swifter/blob/master/Swifter/Swifter.swift#L117
https://github.com/mattdonnelly/Swifter/blob/master/Swifter/Swifter.swift#L145

**Comment by zntfdr** [comment]
You get many .JSONNull because, when connected to a Streaming endpoint, Twitter sends you some blank lines as "keep alive" signals to let you know the connection is fine and that there are simply no Tweets to show you ([source](https://dev.twitter.com/streaming/overview/messages-types#blank_lines)). 

.JSONNull passes the optional building because when you write `let a: JSON? = .JSONNull`, you're assigning an instance of JSON, JSON.JSONNull specifically, to `a`, therefore `a` is not `nil`.
 
Don't be fooled by the keyword "JSON**Null**", it still is a valid instance of the type JSON!

To obtain what you want, all you have to do is create a small extensions similar to the following:

`````swift
extension JSON {
  public var value: JSON? {
    switch self {
      case .JSONNull, .JSONInvalid: return nil
      default: return self
    }
  }
}
`````
..and use it like this:
`````swift
let a: JSON? = .JSONNull
if let b = a where b.value != nil {
  // b is a valid JSON
  ...
} else {
  // a is not a valid JSON
  ...
}
`````
